version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "@dev-productivity"
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "@dev-productivity"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "@dev-productivity"
