site_name: Gradle Community
site_author: Gradle Contributors
site_description: Open-source site for all Gradle community matters
copyright: Copyright &copy; 2025. Gradle® and the Gradlephant logo are registered trademarks of Gradle, Inc.
docs_dir: docs
repo_url: https://github.com/gradle/community
repo_name: gradle/community
edit_uri: edit/main/docs/
site_url: https://community.gradle.org
site_dir: _site

# Theme
theme:
  name: material
  custom_dir: overrides/
  features:
    - content.action.edit
    - content.code.copy
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.follow
    - toc.integrate
  palette:
    - scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    code: Roboto Mono
  favicon: images/logos/gradle.svg
  logo: images/logos/gradle.svg
  icon:
    repo: fontawesome/brands/github

extra_css:
  - assets/css/gradle.css

extra:
  social:
    - icon: fontawesome/brands/slack
      link: https://gradle.org/slack-invite
    - icon: fontawesome/brands/github
      link: https://github.com/gradle
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/gradle
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/gradle
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@Gradle
  analytics:
    provider: custom

nav:
  - Home: README.md
  - Public Roadmap: roadmap/README.md

plugins:
  - search
  - group:
      enabled: true
      plugins:
      - multirepo:
          cleanup: false
          keep_docs_dir: true
          nav_repos:
          - name: roadmap
            import_url: 'https://github.com/gradle/build-tool-roadmap?branch=main&edit_uri=/blob/main/'
            imports: [ "README.md" ]

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - toc:
      permalink: '#'
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables
