name: Continuous Integration

on:
  # We have deploy there
  # push:
  #  branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: read
      pull-requests: write

    env:
      PREVIEW_DOMAIN: gradle.github.io
      PREVIEW_REPO: community-site-preview
      PREVIEW_PATH: ${{ github.event.repository.name }}/pull/${{github.event.number}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Build in the dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/gradle/community.gradle.org-builder
          push: never
          runCmd: |
            mkdocs build
          env: |
            FULL_BUILD=true

      - name: Deploy to PR preview
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ (github.ref != 'refs/heads/main') && (github.event.pull_request.head.repo.full_name == 'gradle/community') }}
        with:
          deploy_key: ${{ secrets.PREVIEW_DEPLOYMENT_KEY }}
          external_repository: gradle/${{ env.PREVIEW_REPO }}
          publish_dir: ./_site
          destination_dir: ${{ env.PREVIEW_PATH }}

      - name: Update comment
        uses: hasura/comment-progress@v2.3.0
        if: ${{ (github.ref != 'refs/heads/main') && (github.event.pull_request.head.repo.full_name == 'gradle/community') }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          number: ${{ github.event.number }}
          id: deploy-preview
          message: > 
            A preview of ${{ github.event.after }} is uploaded and can be seen here:
            
            ✨ https://${{ env.PREVIEW_DOMAIN }}/${{ env.PREVIEW_REPO }}/${{ env.PREVIEW_PATH}}/ ✨
            
            Changes may take a few minutes to propagate. 
